---
development:
  cloud_name: asmarshall
  api_key: '777583955787682'
  api_secret: k827A3-XNm_Fo1Lo0ZLxvRgz7Eg
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: asmarshall
  api_key: '777583955787682'
  api_secret: k827A3-XNm_Fo1Lo0ZLxvRgz7Eg
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: asmarshall
  api_key: '777583955787682'
  api_secret: k827A3-XNm_Fo1Lo0ZLxvRgz7Eg
  enhance_image_tag: true
  static_file_support: false
